services:
  app:
    image: mtg-online-web:local
    build: .
    container_name: mtgate-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Infrastructure config
      - USE_REDIS=true
      - USE_RABBITMQ=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    volumes:
      # Persist all server data (images, metadata)
      - ./server-data:/app/server-data:z
    depends_on:
      - redis
      - rabbitmq
      # - memcached # Uncomment if using memcached

  redis:
    image: redis:alpine
    container_name: mtgate-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mtgate-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  memcached:
    image: memcached:alpine
    container_name: mtgate-memcached
    restart: always
    ports:
      - "11211:11211"

volumes:
  redis-data:
  rabbitmq-data:
