apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mtg-draft-maker.serviceAccountName" . }}
  labels:
    {{- include "mtg-draft-maker.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
